markdown: redcarpet
permalink: pretty
paginate: 25
paginate_path: "page-:num"
exclude:
  - README.md
  - aws-s3.policy

cdn: http://images.rescuepawtraits.ca

sizes:
  portrait: 'width="300" height="452"'
  landscape: 'width="300" height="200"'
